# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Mod Properties
mod_version=1.1.0
maven_group=com.jomlom.nearbycrafting
archives_base_name=nearbycrafting
mod_id=nearbycrafting
mod_name=Nearby Crafting

# Minecraft
minecraft_version=26.2
java_version=25

# Fabric
loader_version=0.19.3
fabric_version=0.158.0+26.2

# NeoForge
neoforge_version=26.2.0.75

# Recipe Book Access
rba_version=1.2.0
